apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
data:
  database-url: BASE64_ENCODED_DATABASE_URL
  aws-access-key-id: BASE64_ENCODED_AWS_ACCESS_KEY_ID
  aws-secret-access-key: BASE64_ENCODED_AWS_SECRET_ACCESS_KEY
  stripe-api-key: BASE64_ENCODED_STRIPE_API_KEY 